language: node_js

node_js:
  - "0.12"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g bower
  - bower i

notifications:
  slack:
    secure: R/eTtR9cndRBexIAhYIAjz8FdnqIQigBaUWmAcJn88XJ3VQmIm5BgOb2fArVn4/a2y491re/A0GleOL4nTHhuPokvQuV4FBTMFdZ1hL4QEMDITwoLpSwJYkR2qaDOcNccW52s59GSN/x+89sebJZjHa6B8RuhJ40/Pd+biPFmk6Q7feBVpIOvlwejxIq0tZ/Z/PPsEmuD+y30NcZOaloAaaUXvqmFpxk8LzQdaSIUfMnJXAxLdSVToSV76Kvzn2KTcJ5XcBDdh51oni24fR6YbUiKltxCHQtDrYnYGYI+PZZkTCG5Tajmc2hTynGXlkK/7OA97eRfZYqVSGP0GKJ653LtbYQ+4ee6JNCcINEjnujfBOw5/oZRL7O7S5zMTN3HyHTQSL1ErI7HEI5XiS4nDKY8O4MvQUEn5Hhz4Pq/DbbfT6Hhzig4jYwTyAuqYA9nA3fGGJhtYS0hBXGhfk5uAp+HH68oPNVde8b3v3OXY2S6/gzntfZpzduVCwhTAwATGATacQLPhrL5296kUVVOqmTqsp4wqgzXQaaBDt3yI11LFExEORJ6oJrUcVzGFR1OXslcKKfoSW3zIxUb+QXS3JvqPhoTRUGQseSsw30ylK/8YL5NStsuP3MCMB54tTwLXnm8S/nfZ2RI2UrteZRvY/Xhb+1Am00JOMxg0HLc84=
